### ISSUE TITLE
Warps reappearing/disappearing

### ISSUE THREAD

**Issue by ultima84** [TheE/MyWarp#43]
I have had a few players on my server reporting issues with MyWarp warps.
In some instances, warps they delete re-appear in their warp lists a day later (often pushing them above their warp limit)
In other instances, warps they create are suddenly removed a day later.
I have viewed the server logs and can see no abnormal behaviour.
We are running Spigot git-Spigot-1d14d5f-7aaa833 (MC: 1.8.3) with MyWarp Build #76
MyWarp is configured to use a remote MySQL database.

I'm wondering if maybe new warp data isn't being written to the MySQL database and only being held in server memory, then removed when the server does its daily restart?

If there's any other information that may be useful to resolve this issue, I'll be happy to provide it.

**Comment by TheE** [comment]
I could not reproduce the issue in a quick test, so it might be a non trivial issue. I think, to track it down, we have two options:

1. If you are able to reproduce the problem, for example because it is always occurs for the same warp or creator _or_ you can reproduce the problem with the same action (removing a warp, restarting your server...) please tell me how and send me a copy of the mywarp database (if you do not want to post them publicly, you can send them to thee@online.de).
2. If you are not able to reproduce the problem it gets more complicated. In that case we could use the query logging of JOOQ to log every query MyWarp sends to the database including results and possible exceptions. Once your players report an issue, we can lookup what happened internally and hopefully spot the issue. Are you familiar with log4j (Minecraft's logging library), do you use a custom logging configuration four your server? If not (or you have no idea what log4j actually is) I will guide you through the process. :smile:

**Comment by Blockbude** [comment]
I can confirm this problem. Seems like everytime when the server is restarting that warps are missing or deleted warps show up again. 
Never used the programs which you named above but I will look into them.

**Comment by TheE** [comment]
I think I found a problem that might prevent warps from being properly saved when the server is shut down: Basically the executor that handles all database communication is terminated by the shutdown of the JVM before it properly finishes the work that's left.

I am not quite sure if this is related to your problem through as I needed to create 2000 warps on the spot and shut down the server directly after doing so to run into the described problem. Still it might happen under normal load when the MySQL server is slow, the server is under heavy load or the user's timing is a but unlucky...

I suggest I fix the problem and you both test again to see if it actually fixes your issues. I will update the issue once there is something to test.

**Comment by TheE** [comment]
Could both of you please give the latest devBuild a shot and report your findings?

**Comment by Blockbude** [comment]
On the first look it seems like the problem was solved correctly. Will report in a few hours again.

**Comment by Blockbude** [comment]
Ok have to corret my self. The bug isn't fixed. The problem also appears when you reload the plugin with a plugin manager so I don't think that it is a performance problem.

**Comment by ultima84** [comment]
I can confirm that this issue is still occurring with the latest dev build.

**Comment by ultima84** [comment]
I asked a player to delete some of their warps. I asked them for the names of the warps and checked if they had been deleted from the MySQL database.
They had not been deleted from the MySQL database. This would explain why the warps are re-appearing on restart.

**Comment by Blockbude** [comment]
The bigger problem is that warps which were created are just disappearing the whole time if you restart the server.

**Comment by TheE** [comment]
The main problem for me is that I am completely unable to reproduce the issue using any combination of warp addition/removal and restart or reload.

If possible, I would like to try enabling JOOQ's debugging output that logs every SQL query the console.
* Create a file named `log4j-config.xml` within the directory that contains the script you use to start the server.
* Past the following content:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN" packages="net.minecraft,com.mojang">
    <Appenders>
        <Console name="WINDOWS_COMPAT" target="SYSTEM_OUT"></Console>
        <Queue name="TerminalConsole">
            <PatternLayout pattern="[%d{HH:mm:ss} %level]: %msg%n" />
        </Queue>
        <RollingRandomAccessFile name="File" fileName="logs/latest.log" filePattern="logs/%d{yyyy-MM-dd}-%i.log.gz">
            <PatternLayout pattern="[%d{HH:mm:ss}] [%t/%level]: %msg%n" />
            <Policies>
                <TimeBasedTriggeringPolicy />
                <OnStartupTriggeringPolicy />
            </Policies>
        </RollingRandomAccessFile>
    </Appenders>
    <Loggers>
        <Root level="debug">
            <filters>
                <MarkerFilter marker="NETWORK_PACKETS" onMatch="DENY" onMismatch="NEUTRAL" />
            </filters>
            <AppenderRef ref="WINDOWS_COMPAT"/>
            <AppenderRef ref="File"/>
            <AppenderRef ref="TerminalConsole"/>
        </Root>
    </Loggers>
</Configuration>
````
This is a copy of Minecraft's default logging file, only the `Root level` has been changed to `debug`.
* Edit the script you use to start your server and add the following parameter to the `java` command: `-Dlog4j.configurationFile=log4j-config.xml`. For example, it could look like this at the end:
````
java -Dlog4j.configurationFile=log4j-config.xml -server -jar craftbukkit-1.7.9-R0.2.jar
````
* Start your server using the edited script.
Now every logger that runs on top of Minecraft's build in logging system will print DEBUG output to the console that you might not see normally.

I am interested in the additional output produced by MyWarp when a warp is edited witch clearly show every query send to the SQL server including possible errors. If you encounter the issue again, please either post your full serverlog and tell me the name of both the player and the warp that are involved or locate the query the player send and post the command and the debug output visible after this command (the more, the better).

**Comment by ultima84** [comment]
Unfortunately I am unable to do this.
My server is hosted by a hosting company. I have access to a control panel and console but not to the start up script.
I did attempt to switch my server over to using a SQLite database to see if that would resolve the issue. But when ever I attempted to import the warps from the MySQL database I received the following error:

5/29/2015 10:13 PM: [MC]: [22:13:20 ERROR]: [MyWarp] The command 'org.bukkit.command.PluginCommand(warp, MyWarp v3.0-SNAPSHOT+jenkins-b77.git-a48904b)' could not be executed.
5/29/2015 10:13 PM: [MC]: me.taylorkelly.mywarp.internal.intake.InvocationCommandException: java.lang.reflect.InvocationTargetException
5/29/2015 10:13 PM: [MC]: 	at me.taylorkelly.mywarp.internal.intake.parametric.ParametricCallable.call(ParametricCallable.java:289) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:3.0-SNAPSHOT+jenkins-b77.git-a48904b]
5/29/2015 10:13 PM: [MC]: 	at me.taylorkelly.mywarp.internal.intake.dispatcher.SimpleDispatcher.call(SimpleDispatcher.java:139) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:3.0-SNAPSHOT+jenkins-b77.git-a48904b]
5/29/2015 10:13 PM: [MC]: 	at me.taylorkelly.mywarp.bukkit.util.parametric.FallbackDispatcher.call(FallbackDispatcher.java:84) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:3.0-SNAPSHOT+jenkins-b77.git-a48904b]
5/29/2015 10:13 PM: [MC]: 	at me.taylorkelly.mywarp.internal.intake.dispatcher.SimpleDispatcher.call(SimpleDispatcher.java:139) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:3.0-SNAPSHOT+jenkins-b77.git-a48904b]
5/29/2015 10:13 PM: [MC]: 	at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onCommand(MyWarpPlugin.java:264) [mywarp-bukkit-3.0-SNAPSHOT-all.jar:3.0-SNAPSHOT+jenkins-b77.git-a48904b]
5/29/2015 10:13 PM: [MC]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: Caused by: java.lang.reflect.InvocationTargetException
5/29/2015 10:13 PM: [MC]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at me.taylorkelly.mywarp.internal.intake.parametric.ParametricCallable$1.call(ParametricCallable.java:264) ~[?:?]
5/29/2015 10:13 PM: [MC]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:132) ~[?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:58) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at me.taylorkelly.mywarp.internal.intake.parametric.ParametricCallable.call(ParametricCallable.java:261) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:3.0-SNAPSHOT+jenkins-b77.git-a48904b]
5/29/2015 10:13 PM: [MC]: 	... 20 more
5/29/2015 10:13 PM: [MC]: Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.Futures.chain(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/base/Function;)Lcom/google/common/util/concurrent/ListenableFuture;
5/29/2015 10:13 PM: [MC]: 	at me.taylorkelly.mywarp.dataconnections.migrators.DataConnectionMigrator.getWarps(DataConnectionMigrator.java:56) ~[?:?]
5/29/2015 10:13 PM: [MC]: 	at me.taylorkelly.mywarp.bukkit.commands.ImportCommands.migrate(ImportCommands.java:135) ~[?:?]
5/29/2015 10:13 PM: [MC]: 	at me.taylorkelly.mywarp.bukkit.commands.ImportCommands.mysql(ImportCommands.java:95) ~[?:?]
5/29/2015 10:13 PM: [MC]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at me.taylorkelly.mywarp.internal.intake.parametric.ParametricCallable$1.call(ParametricCallable.java:264) ~[?:?]
5/29/2015 10:13 PM: [MC]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:132) ~[?:1.7.0_67]
5/29/2015 10:13 PM: [MC]: 	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:58) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
5/29/2015 10:13 PM: [MC]: 	at me.taylorkelly.mywarp.internal.intake.parametric.ParametricCallable.call(ParametricCallable.java:261) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:3.0-SNAPSHOT+jenkins-b77.git-a48904b]
5/29/2015 10:13 PM: [MC]: 	... 20 more

I can confirm that the database details I used in the import command were correct, as they exactly matched the details from the MyWarp config.

**Comment by TheE** [comment]
Sorry, I am rather stressed at the moment so I cannot answer as fast as I want.

First of all, if you where using devBuild#77 you **absolutely** should update. I just fixed a major data-loss that was introduced in the recent build. This might also fix the initial problem, but this remians to be seen.

Next, @ultima84, this issue has nothing to do with your setup. It is caused by Spigot's bundling of a newer Guava version than the original CraftBukkit did. I have registered the problem as #46.

**Comment by ultima84** [comment]
I'm running the latest dev build and are still having the issue.
When a player creates/deletes a warp, should it write that data to the MySQL database immediately?
Because I am noticing that when someone deletes a warp, that warp still exists in the MySQL database. Once the server restarts, that warp then appears again on their warp list.
I attempted to delete the warp directly from the MySQL database, but there appears to be a foreign key preventing me from deleting it. (#1451 - Cannot delete or update a parent row: a foreign key constraint fails (`ultima84_mywarp`.`warp_player_map`, CONSTRAINT `warp_player_map_warp_id_fk` FOREIGN KEY (`warp_id`) REFERENCES `warp` (`warp_id`) ON DELETE NO ACTION ON UPDATE NO ACTION))

**Comment by TheE** [comment]
Interesting, this explains why I was not able to reproduce the problem as it only happens for warps with invitations.

Could you try the latest devBuild? I updated the foreign key behaviour to `CASCADE` so that invitations are also removed when the corresponding warp is removed.

**Comment by Blockbude** [comment]
Seems like it works now but I have another problem since build 79/80:

[12:49:12] [Server thread/ERROR]: [MyWarp] A critical failure has been encountered and MyWarp is unable to continue. MyWarp will be disabled.
me.taylorkelly.mywarp.InitializationException: Failed to get a connection to the database.
	at me.taylorkelly.mywarp.MyWarp.<init>(MyWarp.java:99) ~[MyWarp.jar:3.0-SNAPSHOT+jenkins-b77.git-a48904b]
	at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:151) [MyWarp.jar:3.0-SNAPSHOT+jenkins-b77.git-a48904b]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [skyblock1.jar:git-Spigot-07a5b1b-53433de]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [skyblock1.jar:git-Spigot-07a5b1b-53433de]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [skyblock1.jar:git-Spigot-07a5b1b-53433de]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [skyblock1.jar:git-Spigot-07a5b1b-53433de]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [skyblock1.jar:git-Spigot-07a5b1b-53433de]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [skyblock1.jar:git-Spigot-07a5b1b-53433de]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [skyblock1.jar:git-Spigot-07a5b1b-53433de]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [skyblock1.jar:git-Spigot-07a5b1b-53433de]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [skyblock1.jar:git-Spigot-07a5b1b-53433de]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [skyblock1.jar:git-Spigot-07a5b1b-53433de]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: me.taylorkelly.mywarp.dataconnections.DataConnectionException: Failed to execute migration process.
	at me.taylorkelly.mywarp.dataconnections.MySqlConnection$1.call(MySqlConnection.java:88) ~[?:?]
	at me.taylorkelly.mywarp.dataconnections.MySqlConnection$1.call(MySqlConnection.java:73) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_45]
	... 1 more
Caused by: me.taylorkelly.mywarp.internal.flyway.core.api.FlywayException: Validate failed. Found differences between applied migrations and available migrations: Detected applied migration missing on the classpath: 1.2
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.doValidate(Flyway.java:912) ~[?:?]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.access$400(Flyway.java:50) ~[?:?]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway$1.execute(Flyway.java:817) ~[?:?]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway$1.execute(Flyway.java:811) ~[?:?]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.execute(Flyway.java:1171) ~[?:?]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.migrate(Flyway.java:811) ~[?:?]
	at me.taylorkelly.mywarp.dataconnections.MySqlConnection$1.call(MySqlConnection.java:86) ~[?:?]
	at me.taylorkelly.mywarp.dataconnections.MySqlConnection$1.call(MySqlConnection.java:73) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_45]
	... 1 more
[12:49:12] [Server thread/INFO]: [MyWarp] Disabling MyWarp v3.0-SNAPSHOT+jenkins-b77.git-a48904b

As you can see it says it would be build 77 but it is build 80 what you can see if you use the pluginmanager from AutoSaveWorld the plugin starts without an error:

12:53:11] [Server thread/INFO]: [MyWarp] Enabling MyWarp v3.0-SNAPSHOT+jenkins-b80.git-d967af7
[12:53:11] [Server thread/INFO]: [MyWarp] Using Vault for group support.
[12:53:11] [pool-31-thread-1/INFO]: Database: jdbc:mysql://localhost/skyblock1warp (MySQL 5.5)
[12:53:11] [pool-31-thread-1/INFO]: Validated 3 migrations (execution time 00:00.030s)
[12:53:11] [pool-31-thread-1/INFO]: Current version of schema `skyblock1warp`: 1.2
[12:53:11] [pool-31-thread-1/INFO]: Schema `skyblock1warp` is up to date. No migration necessary.
[12:53:12] [Server thread/INFO]: [MyWarp] Loading warps...                              
[12:53:12] [Server thread/INFO]: Plugin reloaded[m

Hope you can fix this, will report back if warps are still disappearing. I still can't reproduce the event which cause to missing warps :(

**Comment by ultima84** [comment]
I can confirm that deleted warps are remaining deleted with the latest dev build. I have not had any reports of new warps going missing recently either. Will continue to monitor, but I think the issue has been resolved.

I have not experienced the new issue that Blockbude has though.

Thank you for your assistance.

**Comment by Blockbude** [comment]
I know why you don't have the same problem: I did something wrong on my side -.-

This was not a fault of the plugin, sorry.

**Comment by TheE** [comment]
No problem.

I am closing this issue as the bug appears to be resolved. If you notice that some warps are still missing, please reopen or leave comment.
